name: Recreate prod branch from master

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  recreate-prod-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Download code from repo
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Recreate prod branch from master
        run: |
          git push origin --delete prod
          git pull origin master
          git checkout -b prod
          git push origin prod
