name: Recreate prod branch from master

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  recreate-prod-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Download code from repo
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Recreate prod branch from master
        run: |
          git push origin --delete prod
          git pull origin master
          git checkout -b prod
          git push origin prod
      - name: Get latest commit message
        run: echo "COMMIT_MESSAGE=$(git log -1 --format=%s)" >> $GITHUB_ENV
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: .github/workflows/test.yaml
          ref: prod
          inputs: '{ "commit_message": "toJSON(${{ env.COMMIT_MESSAGE }}") }'
  

