name: Target Workflow
run-name: "[${{ github.ref_name }}] CI/CD: ${{ inputs.commit_message || github.event.head_commit.message }}"

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: read


on: 
  push:
    branches:
      - prod
      - dev
  workflow_dispatch:
    inputs:
      commit_message:
        type: string
        required: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      
