name: Target Workflow
run-name: CI/CD to beanstalk environment from ${{ github.ref_name }} branch

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: read


on: 
  push:
    branches:
      - prod
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: git status
