name: Target Workflow
run-name: "[${{ github.ref_name }}] CI/CD: ${{ inputs.message }}"

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: read

on: 
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      message:
        description: 'Last commit message'
        default: github.event.head_commit.message
        required: false
        type: string


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: git status
